apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  namespace: dummy-canary
  labels:
    {{- .Values.labels | toYaml | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- .Values.labels | toYaml | nindent 6 }}
  template:
    metadata:
      labels:
        {{- .Values.labels | toYaml | nindent 8 }}
    spec:
      containers:
      - name: dummy
        image: ghcr.io/fredr/dummy:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 3000
          name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
